config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins,controllers:{sessions: "admins/sessions"}
  devise_for :users, controllers:{sessions: "users/sessions"}
  resources :posts do
     resources :comments 
      end
    root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments , dependent: :destroy
    validates_presence_of :title
    validates_presence_of :body
    validates_length_of :title, :in => 10..50, :message => "el titulo es demasiado corto o largo"
    
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :auth_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def auth_user!
        if admin_signed_in?
            authenticate_admin!
        else
            authenticate_user!
        end
    end
    
    def create
        end

    # GET /posts
    # GET /posts.json
    
    
    
    def index
        if admin_signed_in?
            @posts = Post.all
        else
            @posts = current_user.post
        end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end



    # GET /posts/new
    def new
        if can? :create, Post
            @post = Post.new
        else
            flash[:alert] = "No tiene permisos para agregar un nuevo post"
            redirect_to :action => "index"
        end
     end

    # GET /posts/1/edit
    def edit
        if can? :edit, Post
        else
            flash[:alert] = "No tiene permisos para editar un nuevo post"
            redirect_to :action => "index"
        end
    end

    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(post_params)

        respond_to do |format|
            if @post.save
                format.html { redirect_to @post, notice: 'Post was successfully created.' }
                format.json { render :show, status: :created, location: @post }
            else
                format.html { render :new }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            if @post.update(post_params)
                format.html { redirect_to @post, notice: 'Post was successfully updated.' }
                format.json { render :show, status: :ok, location: @post }
            else
                format.html { render :edit }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
            format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
	<div class="small-6 column">
		<div class="field">
			<%= f.label :title %><br>
			<%= f.text_field :title,:class => "validate[required]" %>
		</div>
		<div class="field">
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	</div>
</div>
  
<% end %>

app/views/posts/_navigation.html.erb
<nav class = "top-bar" data-topbar role = "navigation">
    <ul class = "title-area">
        <li class = "name">
            <h1>Blog</h1>
        </li>
    </ul>
    <section class="top-bar-section">
        <ul class = "left">
            <li class = "has-dropdown not-click"><a hre="#">Menu</a>
                <ul class = "dropdown">
                    <li class="parent-link show-or-small-only"><a class="parent-link js-generated" href="#">Acciones</a></li>
                    <li><%= link_to 'Inicio', controller:'/posts',action:'index' %></li>
                    <li><%= link_to 'Nuevo', controller:'/posts',action:'new' %></li>
                </ul>
            </li>
            <li class="divider"></li>
        </ul>
        <ul class = "right">
            <%if user_signed_in? %>
            <li><a>Logged in as <%= current_user.email %></a></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            <% elsif admin_signed_in? %>
            <li><a>Logged in as <%= current_user.email %></a></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            <% else %>
            <li><%=link_to'Login',new_user_session_path%></li>
            <li><%=link_to'Sign up',new_user_registration_path%></li>
            
            <% end %>
            
        </ul>
    </section>
</nav>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td>
            <% if can? :destroy, post %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> 
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Body:</strong>
    <%= @post.body %>
</p>

<div id="comments">
    <%= render :partial => @post.comments.reverse %>
</div>

<%=form_for([@post, Comment.new], remote:true) do |f|%>
<p><%= f.label:body, "New Comment"%><br/>
    <%=f.text_area :body %>
</p>
<p><%= f.submit "Add Comment" %></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>